version: '3'
services:
  api:
    image: kun391/phpup:1.1
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - db
    volumes:
      - ./src:/var/www/app:delegated
      - ./deployment/certs/cert.pem:/etc/nginx/www-ssl/certificate.crt
      - ./deployment/certs/private.key:/etc/nginx/www-ssl/privateKey.key
      - ./deployment/configs/queue.conf:/etc/supervisor/conf.d/queue.conf
      - ./deployment/configs/nginx.conf:/etc/nginx/sites-enabled/default.conf
      - ./deployment/configs/nginx.ssl.conf:/etc/nginx/sites-enabled/default.ssl.conf
      - ./deployment/configs/crontab.conf:/etc/crontabs/root
    environment:
      - PHP_MEM_LIMIT=${PHP_MEM_LIMIT}
    restart: on-failure
  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${MYSQL_DATABASE}
      POSTGRES_USER: ${MYSQL_USER}
      POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure
  # container for UI database management
  phpmyadmin:
    image: dpage/pgadmin4
    ports:
      - ${PHPADMIN_PORT}:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: on-failure
