<?php

/*
 * You can place your custom package configuration in here.
 */
return [
    'MODEL_COLLECTIONS' => [
        "GGPHP\Kiosk\Models\Kiosk" => "Kiosk",
        "GGPHP\RolePermission\Models\City" => "Thành phố",
        "GGPHP\RolePermission\Models\Store" => "Cửa hàng",
        "GGPHP\RolePermission\Models\Role" => "Vai Trò",
        "GGPHP\RolePermission\Models\Permission" => "Quyền",
        "GGPHP\Notifications\Models\Notification" => "Thông báo",
        "GGPHP\Timekeeping\Models\Timekeeping" => "Chấm công",
        "GGPHP\LateEarly\Models\LateEarlyTimeConfig" => "Cấu hình đi trễ về sớm",
        "GGPHP\LateEarly\Models\LateEarly" => "Đi trễ về sớm",
        "GGPHP\Faults\Models\Fault" => "Lỗi",
        "GGPHP\Faults\Models\FaultContent" => "Nội dung lỗi",
        "GGPHP\Faults\Models\FaultType" => "Loại lỗi",
        "GGPHP\ShiftSchedule\Models\ScheduleChangelog" => "Lịch sử thay đổi lịch làm việc",
        "GGPHP\ShiftSchedule\Models\Schedule" => "Lịch làm việc",
        "GGPHP\ShiftSchedule\Models\ShiftDetail" => "Chi tiết ca",
        "GGPHP\ShiftSchedule\Models\ScheduleRequestDetail" => "Chi tiết đề xuất sửa lịch việc",
        "GGPHP\ShiftSchedule\Models\ScheduleRequestReason" => "Lý do đề xuất sửa lịch",
        "GGPHP\ShiftSchedule\Models\ScheduleException" => "Lịch ngoại lệ",
        "GGPHP\ShiftSchedule\Models\ScheduleRepeat" => "Lặp lại của lịch",
        "GGPHP\ShiftSchedule\Models\ScheduleRequest" => "Đề xuất sửa lịch",
        "GGPHP\ShiftSchedule\Models\Shift" => "Ca",
        "GGPHP\ShiftSchedule\Models\ScheduleRequestOrigin" => "Lịch làm việc cũ",
        "GGPHP\Absent\Models\Absent" => "Nghỉ phép",
        "GGPHP\Absent\Models\AbsentReason" => "Lý do nghỉ phép",
        "GGPHP\Absent\Models\AbsentType" => "Loại nghỉ phép",
        "GGPHP\Review\Models\ReviewForm" => "Form đánh giá",
        "GGPHP\Review\Models\ReviewCriteria" => "Tiêu chí đánh giá",
        "GGPHP\Review\Models\ReviewPersonalTargetReviewerDetail" => "Chi tiết điểm người đánh giá",
        "GGPHP\Review\Models\ReviewProductivity" => "Đánh giá năng suất",
        "GGPHP\Review\Models\ReviewProductivityDetail" => "Chi tiết đánh giá năng suất",
        "GGPHP\Review\Models\ReviewPersonalTargetReviewer" => "Người đánh giá",
        "GGPHP\Review\Models\ReviewPersonalTarget" => "Đánh giá tháng",
        "GGPHP\MagneticCard\Models\MagneticCard" => "Thẻ nhân viên",
        "GGPHP\FingerprintTimekeeper\Models\FingerprintTimekeeper" => "Máy chấm công",
        "GGPHP\Division\Models\WorkForm" => "Hình thức làm việc",
        "GGPHP\Division\Models\Division" => "Bộ phận",
        "GGPHP\Division\Models\Rank" => "Chức vụ",
        "GGPHP\Division\Models\Position" => "Cấp bậc",
        "GGPHP\Division\Models\RankPositionInformation" => "Thông tin cấp bậc, chức vụ",
        "GGPHP\Decision\Models\Decision" => "Thông báo, quyết định",
        "GGPHP\Profiles\Models\Insurrance" => "Bảo hiểm",
        "GGPHP\Profiles\Models\SalaryInformation" => "Thông tin lương",
        "GGPHP\Profiles\Models\LabourContract" => "Hợp đồng lao động",
        "GGPHP\Profiles\Models\WorkTime" => "Thời gian làm việc",
        "GGPHP\Profiles\Models\TimekeepingConfig" => "Cấu hình chấm công",
        "GGPHP\Profiles\Models\SabbaticalLeave" => "Xin nghỉ việc",
        "GGPHP\Profiles\Models\ContactInformation" => "Thông tin liên lạc",
        "GGPHP\Profiles\Models\Education" => "Học vấn",
        "GGPHP\Profiles\Models\BankInformation" => "Thôn tin ngân hàng",
        "GGPHP\Profiles\Models\WorkHistory" => "Lịch sử làm việc",
        "GGPHP\Profiles\Models\HealthInformation" => "Thông tin sức khỏe",
        "GGPHP\Profiles\Models\Transfer" => "Điều chuyển",
        "GGPHP\SubtractionTime\Models\SubtractionTime" => "Công trừ",
        "GGPHP\SubtractionTime\Models\SubtractionTimeDetail" => "Chi tiết công trừ",
        "GGPHP\Fingerprint\Models\Fingerprint" => "Vân tay",
        "GGPHP\AdditionalTime\Models\AdditionalTimeDetail" => "Chi tiết công thêm",
        "GGPHP\AdditionalTime\Models\AdditionalTime" => "Công thêm",
        "GGPHP\Approval\Models\ApprovalConfirmation" => "Duyệt",
        "GGPHP\Approval\Models\ApprovalRequest" => "Yêu cầu duyệt",
        "GGPHP\Suggest\Models\SuggestOvertime" => "Đề xuất tăng ca, tăng cường",
        "GGPHP\Suggest\Models\SuggestReason" => "Lý do đề xuất",
        "GGPHP\Suggest\Models\Suggest" => "Đề xuất",
        "GGPHP\Suggest\Models\SuggestSalaryIncreaseDetail" => "Đề xuất tăng lương",
        "GGPHP\Suggest\Models\SuggestLog" => "Nhật ký đề xuất",
        "GGPHP\Suggest\Models\SuggestCategory" => "Danh mục đề xuất",
        "GGPHP\Suggest\Models\SuggestRecruitmentDetail" => "Đề xuất chi tiết tuyển dụng",
        "GGPHP\Users\Models\User" => "Nhân viên",
    ],
];
