// eslint-disable-next-line import/extensions
import Cookies from 'universal-cookie';
import { permissions, FLATFORM, ACTION } from '../../config/permissions';
import animationImage from './animation.json';

const cookies = new Cookies();
export const feature = {
  FEATURES: [
    {
      title: 'Thông báo',
      src: '/images/home/news.svg',
      animation: animationImage.notification,
      url: '/thong-bao/danh-sach',
      permission: [permissions.THONGBAO],
    },
    {
      title: 'Hồ sơ đối tượng',
      src: '/images/home/contact.svg',
      animation: animationImage.profile,
      url: '/ho-so-doi-tuong',
      permission: [permissions.WEB_HSDT_VIEW],
    },
    {
      title: 'Phân lớp',
      src: '/images/home/pin.svg',
      animation: animationImage.allotment,
      url: '/phan-bo',
      permission: [permissions.WEB_PHANLOP_VIEW],
    },
    // {
    //   title: 'Trao đổi',
    //   src: '/images/home/speech.svg',
    //   animation: animationImage.communication,
    //   url: '/trao-doi',
    //   permission: [permissions.TD],
    // },
    {
      title: 'Hình ảnh',
      src: '/images/home/movies.svg',
      animation: animationImage.record,
      url: '/hinh-anh/danh-sach',
      permission: [permissions.HA],
    },
    {
      title: 'Dặn dò từ phụ huynh',
      src: '/images/home/pages.svg',
      animation: animationImage.note,
      url: '/ghi-chu',
      permission: [`${FLATFORM.WEB}${permissions.DANDO}${ACTION.VIEW}`],
    },
    {
      title: 'Điểm danh trẻ',
      src: '/images/home/note.svg',
      animation: animationImage.attendance,
      url: '/diem-danh',
      permission: [permissions.WEB_DIEMDANH_VIEW],
    },
    {
      title: 'Chương trình học',
      src: '/images/home/spreadsheet.svg',
      animation: animationImage.programStudy,
      url: '/chuong-trinh-hoc',
      permission: [`${FLATFORM.WEB}${permissions.CTH}${ACTION.VIEW}`],
    },
    {
      title: 'Bus',
      src: '/images/home/road.svg',
      animation: animationImage.bus,
      url: '/quan-ly-phuong-tien',
      permission: [permissions.BUS],
    },
    {
      title: 'Y tế',
      src: '/images/home/balloons.svg',
      animation: animationImage.medical,
      url: '/y-te/danh-sach-nhan-thuoc',
      permission: [permissions.YTE],
    },
    {
      title: 'Thời khóa biểu',
      src: '/images/home/calendar.svg',
      animation: animationImage.calendar,
      url: '/thoi-khoa-bieu',
      permission: [permissions.WEB_TKB_VIEW],
    },
    {
      title: 'Bếp',
      src: '/images/home/cooking.svg',
      animation: animationImage.kitchen,
      url: '/thuc-don',
      permission: [permissions.BEP],
    },
    {
      title: 'Biểu phí',
      src: '/images/home/currency.svg',
      animation: animationImage.tariffs,
      url: '/bieu-phi',
      permission: [permissions.BIEUPHI],
    },
    {
      title: 'Bảng lương',
      src: '/images/home/drive.svg',
      animation: animationImage.salary,
      url: '/bang-luong',
      permission: [permissions.BANGLUONG],
    },
    {
      title: 'Sức khỏe',
      src: '/images/home/tumblr.svg',
      animation: animationImage.health,
      url: '/suc-khoe',
      permission: [`${FLATFORM.WEB}${permissions.SUCKHOE}${ACTION.VIEW}`],
    },
    {
      title: 'Quản trị nhân sự',
      src: '/images/home/hrm.svg',
      animation: animationImage.administration,
      url: '/quan-ly-nhan-su',
      permission: [permissions.HRM],
    },
    {
      title: 'Chính sách phí',
      src: '/images/home/diploma.svg',
      animation: animationImage.feePolicy,
      url: '/chinh-sach-phi',
      permission: [permissions.CHINHSACHPHI],
    },
    {
      title: 'Phát triển thể chất',
      src: '/images/home/physical.svg',
      animation: animationImage.physical,
      url: '/phat-trien-the-chat',
      permission: [permissions.THECHAT],
    },
    {
      title: 'CRM',
      src: '/images/home/crm.svg',
      animation: animationImage.crm,
      url: '/crm',
      permission: [permissions.CRM],
    },
    {
      title: 'Cấu hình',
      src: '/images/home/gear.svg',
      animation: animationImage.setting,
      url: '/cau-hinh',
      permission: [permissions.CAUHINH],
    },
    {
      title: 'Camera AI',
      src: '/images/home/chip.svg',
      animation: animationImage.cameraAI,
      url: `${URL_AI}/verify-token?token=${cookies.get('access_token')}`,
      target: true,
      permission: [permissions.CAMERAAI],
      key: 'AI',
    },
    {
      title: 'Sự phát triển của trẻ',
      src: '/images/home/childDevelop.svg',
      animation: animationImage.childDevelop,
      url: '/su-phat-trien-cua-tre',
      authority: [`${FLATFORM.WEB}${permissions.SPTCT}${ACTION.VIEW}`],
    },
    {
      title: 'Chiến dịch Email',
      src: '/images/home/emailMarketing.svg',
      animation: animationImage.emailMarketting,
      url: URL_EMAIL_MARKETING,
      target: true,
      permission: [permissions.CAMERAAI],
    },
    {
      title: 'English',
      src: '/images/home/english.svg',
      animation: animationImage.english,
      url: '/english',
      permission: [permissions.WEB_TIENGANH_VIEW],
    },
    {
      title: 'Báo cáo ERP',
      src: '/images/home/training.svg',
      animation: animationImage.report,
      url: '/bao-cao-erp',
      permission: [permissions.WEB_BAO_CAO_ERP_VIEW],
    },
    {
      title: 'Thể chất',
      src: '/images/home/iconPhysical.svg',
      animation: animationImage.physicalItem,
      url: '/the-chat',
      permission: [permissions.WEB_THECHAT_VIEW],
    },
    {
      title: 'Phân quyền V2',
      src: '/images/home/gear.svg',
      animation: animationImage.setting,
      url: URL_CONFIGURATIONV2,
      target: true,
      permission: [permissions.WEB_PHANQUYENVER2_VIEW],
      key: 'CONFIGURATIONV2',
    },
  ],
};

export default feature;
