import animationImage from "./animation.json";

export const feature = {
  FEATURES: [
    {
      title: 'Thông báo',
      src: '/images/home/news.svg',
      animation: animationImage.notification,
      url: '/thong-bao/danh-sach',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Hồ sơ đối tượng',
      src: '/images/home/contact.svg',
      animation: animationImage.profile,
      url: '/ho-so-doi-tuong',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Phân bổ',
      src: '/images/home/pin.svg',
      animation: animationImage.allotment,
      url: '/phan-bo',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Trao đổi',
      src: '/images/home/speech.svg',
      animation: animationImage.communication,
      url: '/trao-doi',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Ghi nhận',
      src: '/images/home/movies.svg',
      animation: animationImage.record,
      url: '/ghi-nhan/danh-sach',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Ghi chú',
      src: '/images/home/pages.svg',
      animation: animationImage.note,
      url: '/ghi-chu',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Điểm danh trẻ',
      src: '/images/home/note.svg',
      animation: animationImage.attendance,
      url: '/diem-danh',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Chương trình học',
      src: '/images/home/spreadsheet.svg',
      animation: animationImage.programStudy,
      url: '/chuong-trinh-hoc/danh-gia-hoc-tap',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Bus',
      src: '/images/home/road.svg',
      animation: animationImage.bus,
      url: '/quan-ly-phuong-tien',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Y tế',
      src: '/images/home/balloons.svg',
      animation: animationImage.medical,
      url: '/y-te',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Thời khóa biểu',
      src: '/images/home/calendar.svg',
      animation: animationImage.calendar,
      url: '/thoi-khoa-bieu',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Bếp',
      src: '/images/home/cooking.svg',
      animation: animationImage.kitchen,
      url: '/thuc-don',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Biếu phí',
      src: '/images/home/currency.svg',
      animation: animationImage.tariffs,
      url: '/',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Bảng lương',
      src: '/images/home/drive.svg',
      animation: animationImage.notification,
      url: '/',
      permission: ['ADMIN', 'HRM'],
    },
    {
      title: 'Sức khỏe',
      src: '/images/home/tumblr.svg',
      animation: animationImage.health,
      url: '/suc-khoe',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Quản trị nhân sự',
      src: '/images/home/hrm.svg',
      animation: animationImage.notification,
      url: '/quan-ly-nhan-su',
      permission: ['ADMIN', 'HRM'],
    },
    {
      title: 'Chính sách phí',
      src: '/images/home/diploma.svg',
      animation: animationImage.feePolicy,
      url: '/chinh-sach-phi',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Cấu hình',
      src: '/images/home/gear.svg',
      animation: animationImage.setting,
      url: '/cau-hinh',
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
    {
      title: 'Camera AI',
      src: '/images/home/chip.svg',
      animation: animationImage.cameraAI,
      url: URL_AI,
      target: true,
      permission: ['ADMIN', 'TEACHER', 'PARENT', 'PRINCIPAL', 'ALL'],
    },
  ],
};

export default feature;
