export const permissions = {
  TONGQUAN: 'TONGQUAN',
  THONGBAO: 'THONGBAO',
  HSDT: 'HSDT',
  PB: 'PB',
  TD: 'TD',
  HA: 'HA',
  DD: 'DD',
  CTH: 'CTH',
  BUS: 'BUS',
  YTE: 'YTE',
  TKB: 'TKB',
  BEP: 'BEP',
  BIEUPHI: 'BIEUPHI',
  CHINHSACHPHI: 'CHINHSACHPHI',
  BANGLUONG: 'BANGLUONG',
  SUCKHOE: 'SUCKHOE',
  HRM: 'HRM',
  CAUHINH: 'CAUHINH',
  CAMERAAI: 'CAMERAAI',
  GHICHU: 'GHICHU',
  YKIEN: 'YKIEN',
  HETHONG: 'HETHONG',
  THECHAT: 'THECHAT',
  CRM: 'CRM',
  SUPHATTRIENCUATRE: 'SUPHATTRIENCUATRE',

  //Tiếng anh
  WEB_TIENGANH_VIEW: 'WEB_TIENGANH_VIEW',

  WEB_TIENGANH_DANHGIATHANG_VIEW: 'WEB_TIENGANH_DANHGIATHANG_VIEW',
  WEB_TIENGANH_DANHGIATHANG_CHUADUYET_EDIT: 'WEB_TIENGANH_DANHGIATHANG_CHUADUYET_EDIT',
  WEB_TIENGANH_DANHGIATHANG_CHUADANHGIA_CREATE: 'WEB_TIENGANH_DANHGIATHANG_CHUADANHGIA_CREATE',

  WEB_TIENGANH_DANHGIADINHKY_VIEW: 'WEB_TIENGANH_DANHGIADINHKY_VIEW',
  WEB_TIENGANH_DANHGIADINHKY_CHUADUYET_EDIT: 'WEB_TIENGANH_DANHGIADINHKY_CHUADUYET_EDIT',
  WEB_TIENGANH_DANHGIADINHKY_CHUADANHGIA_CREATE: 'WEB_TIENGANH_DANHGIADINHKY_CHUADANHGIA_CREATE',

  WEB_TIENGANH_THOIKHOABIEU_VIEW: 'WEB_TIENGANH_THOIKHOABIEU_VIEW',

  WEB_TIENGANH_QUANLYBAIGIANG_VIEW: 'WEB_TIENGANH_QUANLYBAIGIANG_VIEW',
  WEB_TIENGANH_QUANLYBAIGIANG_CREATE: 'WEB_TIENGANH_QUANLYBAIGIANG_CREATE',
  WEB_TIENGANH_QUANLYBAIGIANG_EDIT: 'WEB_TIENGANH_QUANLYBAIGIANG_EDIT',
  WEB_TIENGANH_QUANLYBAIGIANG_DETAIL: 'WEB_TIENGANH_QUANLYBAIGIANG_DETAIL',

  WEB_TIENGANH_QUANLYTIEUCHI_VIEW: 'WEB_TIENGANH_QUANLYTIEUCHI_VIEW',
  WEB_TIENGANH_QUANLYTIEUCHI_CREATE: 'WEB_TIENGANH_QUANLYTIEUCHI_CREATE',
  WEB_TIENGANH_QUANLYTIEUCHI_EDIT: 'WEB_TIENGANH_QUANLYTIEUCHI_EDIT',
  WEB_TIENGANH_QUANLYTIEUCHI_DETAIL: 'WEB_TIENGANH_QUANLYTIEUCHI_DETAIL',

  WEB_TIENGANH_QUANLYCOMMENT_VIEW: 'WEB_TIENGANH_QUANLYCOMMENT_VIEW',
  WEB_TIENGANH_QUANLYCOMMENT_CREATE: 'WEB_TIENGANH_QUANLYCOMMENT_CREATE',
  WEB_TIENGANH_QUANLYCOMMENT_EDIT: 'WEB_TIENGANH_QUANLYCOMMENT_EDIT',
  WEB_TIENGANH_QUANLYCOMMENT_DETAIL: 'WEB_TIENGANH_QUANLYCOMMENT_DETAIL',

  WEB_TIENGANH_QUANLYPHANMUC_VIEW: 'WEB_TIENGANH_QUANLYPHANMUC_VIEW',
  WEB_TIENGANH_QUANLYPHANMUC_CREATE: 'WEB_TIENGANH_QUANLYPHANMUC_CREATE',
  WEB_TIENGANH_QUANLYPHANMUC_EDIT: 'WEB_TIENGANH_QUANLYPHANMUC_EDIT',
  WEB_TIENGANH_QUANLYPHANMUC_DETAIL: 'WEB_TIENGANH_QUANLYPHANMUC_DETAIL',

  WEB_TIENGANH_KICHBANDANHGIA_VIEW: 'WEB_TIENGANH_KICHBANDANHGIA_VIEW',
  WEB_TIENGANH_KICHBANDANHGIA_CREATE: 'WEB_TIENGANH_KICHBANDANHGIA_CREATE',
  WEB_TIENGANH_KICHBANDANHGIA_EDIT: 'WEB_TIENGANH_KICHBANDANHGIA_EDIT',
  WEB_TIENGANH_KICHBANDANHGIA_DETAIL: 'WEB_TIENGANH_KICHBANDANHGIA_DETAIL',

  WEB_TIENGANH_SCHEDULE_VIEW: 'WEB_TIENGANH_SCHEDULE_VIEW',
  WEB_BAO_CAO_ERP_VIEW: 'WEB_BAO_CAO_ERP_VIEW',
};
export default permissions;
