export const permissions = {
  TONGQUAN: 'TONGQUAN',
  THONGBAO: 'THONGBAO',
  HSDT: 'HSDT',
  PB: 'PB',
  TD: 'TD',
  HA: 'HA',
  DD: 'DD',
  CTH: 'CTH',
  BUS: 'BUS',
  YTE: 'YTE',
  TKB: 'TKB',
  BEP: 'BEP',
  BIEUPHI: 'BIEUPHI',
  CHINHSACHPHI: 'CHINHSACHPHI',
  BANGLUONG: 'BANGLUONG',
  SUCKHOE: 'SUCKHOE',
  HRM: 'HRM',
  CAUHINH: 'CAUHINH',
  CAMERAAI: 'CAMERAAI',
  GHICHU: 'GHICHU',
  YKIEN: 'YKIEN',
  HETHONG: 'HETHONG',
  THECHAT: 'THECHAT',
  CRM: 'CRM'
};
export default permissions;
