const FLATFORM = {
  WEB: 'WEB_',
};

const ACTION = {
  CREATE: '_CREATE',
  VIEW: '_VIEW',
  DETAIL: '_DETAIL',
  EDIT: '_EDIT',
  DELETE: '_DELETE',
  APPROVE: '_APPROVE',
  SEND: '_SEND',
  IMPORT: '_IMPORT',
  EXPORT: '_EXPORT',
  DOWNLOAD: '_DOWNLOAD',
};

export { FLATFORM, ACTION };

export const permissions = {
  TONGQUAN: 'TONGQUAN',
  THONGBAO: 'THONGBAO',
  HSDT: 'HSDT',
  PB: 'PB',
  TD: 'TD',
  HA: 'HA',
  DD: 'DD',
  BUS: 'BUS',
  YTE: 'YTE',
  TKB: 'TKB',
  BEP: 'BEP',
  BIEUPHI: 'BIEUPHI',
  CHINHSACHPHI: 'CHINHSACHPHI',
  BANGLUONG: 'BANGLUONG',
  HRM: 'HRM',
  CAUHINH: 'CAUHINH',
  CAMERAAI: 'CAMERAAI',
  GHICHU: 'GHICHU',
  YKIEN: 'YKIEN',
  HETHONG: 'HETHONG',
  THECHAT: 'THECHAT',
  CRM: 'CRM',
  SUPHATTRIENCUATRE: 'SUPHATTRIENCUATRE',

  //Tiếng anh
  WEB_TIENGANH_VIEW: 'WEB_TIENGANH_VIEW',

  WEB_TIENGANH_DANHGIATHANG_VIEW: 'WEB_TIENGANH_DANHGIATHANG_VIEW',
  WEB_TIENGANH_DANHGIATHANG_CHUADUYET_EDIT: 'WEB_TIENGANH_DANHGIATHANG_CHUADUYET_EDIT',
  WEB_TIENGANH_DANHGIATHANG_CHUADANHGIA_CREATE: 'WEB_TIENGANH_DANHGIATHANG_CHUADANHGIA_CREATE',

  WEB_TIENGANH_DANHGIADINHKY_VIEW: 'WEB_TIENGANH_DANHGIADINHKY_VIEW',
  WEB_TIENGANH_DANHGIADINHKY_CHUADUYET_EDIT: 'WEB_TIENGANH_DANHGIADINHKY_CHUADUYET_EDIT',
  WEB_TIENGANH_DANHGIADINHKY_CHUADANHGIA_CREATE: 'WEB_TIENGANH_DANHGIADINHKY_CHUADANHGIA_CREATE',

  WEB_TIENGANH_THOIKHOABIEU_VIEW: 'WEB_TIENGANH_THOIKHOABIEU_VIEW',

  WEB_TIENGANH_QUANLYBAIGIANG_VIEW: 'WEB_TIENGANH_QUANLYBAIGIANG_VIEW',
  WEB_TIENGANH_QUANLYBAIGIANG_CREATE: 'WEB_TIENGANH_QUANLYBAIGIANG_CREATE',
  WEB_TIENGANH_QUANLYBAIGIANG_EDIT: 'WEB_TIENGANH_QUANLYBAIGIANG_EDIT',
  WEB_TIENGANH_QUANLYBAIGIANG_DETAIL: 'WEB_TIENGANH_QUANLYBAIGIANG_DETAIL',

  WEB_TIENGANH_QUANLYTIEUCHI_VIEW: 'WEB_TIENGANH_QUANLYTIEUCHI_VIEW',
  WEB_TIENGANH_QUANLYTIEUCHI_CREATE: 'WEB_TIENGANH_QUANLYTIEUCHI_CREATE',
  WEB_TIENGANH_QUANLYTIEUCHI_EDIT: 'WEB_TIENGANH_QUANLYTIEUCHI_EDIT',
  WEB_TIENGANH_QUANLYTIEUCHI_DETAIL: 'WEB_TIENGANH_QUANLYTIEUCHI_DETAIL',

  WEB_TIENGANH_QUANLYCOMMENT_VIEW: 'WEB_TIENGANH_QUANLYCOMMENT_VIEW',
  WEB_TIENGANH_QUANLYCOMMENT_CREATE: 'WEB_TIENGANH_QUANLYCOMMENT_CREATE',
  WEB_TIENGANH_QUANLYCOMMENT_EDIT: 'WEB_TIENGANH_QUANLYCOMMENT_EDIT',
  WEB_TIENGANH_QUANLYCOMMENT_DETAIL: 'WEB_TIENGANH_QUANLYCOMMENT_DETAIL',

  WEB_TIENGANH_QUANLYPHANMUC_VIEW: 'WEB_TIENGANH_QUANLYPHANMUC_VIEW',
  WEB_TIENGANH_QUANLYPHANMUC_CREATE: 'WEB_TIENGANH_QUANLYPHANMUC_CREATE',
  WEB_TIENGANH_QUANLYPHANMUC_EDIT: 'WEB_TIENGANH_QUANLYPHANMUC_EDIT',
  WEB_TIENGANH_QUANLYPHANMUC_DETAIL: 'WEB_TIENGANH_QUANLYPHANMUC_DETAIL',

  WEB_TIENGANH_KICHBANDANHGIA_VIEW: 'WEB_TIENGANH_KICHBANDANHGIA_VIEW',
  WEB_TIENGANH_KICHBANDANHGIA_CREATE: 'WEB_TIENGANH_KICHBANDANHGIA_CREATE',
  WEB_TIENGANH_KICHBANDANHGIA_EDIT: 'WEB_TIENGANH_KICHBANDANHGIA_EDIT',
  WEB_TIENGANH_KICHBANDANHGIA_DETAIL: 'WEB_TIENGANH_KICHBANDANHGIA_DETAIL',

  WEB_TIENGANH_SCHEDULE_VIEW: 'WEB_TIENGANH_SCHEDULE_VIEW',
  WEB_BAO_CAO_ERP_VIEW: 'WEB_BAO_CAO_ERP_VIEW',

  //Thể chất
  WEB_THECHAT_VIEW: 'WEB_THECHAT_VIEW',
  WEB_THECHAT_QUANLYBAIHOC_VIEW: 'WEB_THECHAT_QUANLYBAIHOC_VIEW',
  WEB_THECHAT_QUANLYBAIHOC_CREATE: 'WEB_THECHAT_QUANLYBAIHOC_CREATE',
  WEB_THECHAT_QUANLYBAIHOC_EDIT: 'WEB_THECHAT_QUANLYBAIHOC_EDIT',
  WEB_THECHAT_QUANLYBAIHOC_DETAIL: 'WEB_THECHAT_QUANLYBAIHOC_DETAIL',
  WEB_THECHAT_QUANLYNHANXET_VIEW: 'WEB_THECHAT_QUANLYNHANXET_VIEW',
  WEB_THECHAT_QUANLYNHANXET_CREATE: 'WEB_THECHAT_QUANLYNHANXET_CREATE',
  WEB_THECHAT_QUANLYNHANXET_EDIT: 'WEB_THECHAT_QUANLYNHANXET_EDIT',
  WEB_THECHAT_QUANLYNHANXET_DETAIL: 'WEB_THECHAT_QUANLYNHANXET_DETAIL',
  WEB_THECHAT_QUANLYMONDANHGIA_VIEW: 'WEB_THECHAT_QUANLYMONDANHGIA_VIEW',
  WEB_THECHAT_QUANLYMONDANHGIA_CREATE: 'WEB_THECHAT_QUANLYMONDANHGIA_CREATE',
  WEB_THECHAT_QUANLYMONDANHGIA_EDIT: 'WEB_THECHAT_QUANLYMONDANHGIA_EDIT',
  WEB_THECHAT_QUANLYMONDANHGIA_DETAIL: 'WEB_THECHAT_QUANLYMONDANHGIA_DETAIL',
  WEB_THECHAT_CAUHINHDANHGIA_VIEW: 'WEB_THECHAT_CAUHINHDANHGIA_VIEW',
  WEB_THECHAT_CAUHINHDANHGIA_CREATE: 'WEB_THECHAT_CAUHINHDANHGIA_CREATE',
  WEB_THECHAT_CAUHINHDANHGIA_EDIT: 'WEB_THECHAT_CAUHINHDANHGIA_EDIT',
  WEB_THECHAT_CAUHINHDANHGIA_DETAIL: 'WEB_THECHAT_CAUHINHDANHGIA_DETAIL',
  WEB_THECHAT_NHANXETTIETHOC_VIEW: 'WEB_THECHAT_NHANXETTIETHOC_VIEW',
  WEB_THECHAT_DOLUONGDINHKY_VIEW: 'WEB_THECHAT_DOLUONGDINHKY_VIEW',

  WEB_PHANQUYENVER2_VIEW: 'WEB_PHANQUYENVER2_VIEW',

  //Hồ sơ đối tượng
  WEB_HSDT_VIEW: 'WEB_HSDT_VIEW',
  WEB_HSDT_HOCSINH_VIEW: 'WEB_HSDT_HOCSINH_VIEW',
  WEB_HSDT_HOCSINH_CREATE: 'WEB_HSDT_HOCSINH_CREATE',
  WEB_HSDT_HOCSINH_DETAIL: 'WEB_HSDT_HOCSINH_DETAIL',
  WEB_HSDT_HOCSINH_EDIT: 'WEB_HSDT_HOCSINH_EDIT',
  WEB_HSDT_HOSODALUUTRU_HOCSINH_DETAIL: 'WEB_HSDT_HOSODALUUTRU_HOCSINH_DETAIL',
  WEB_HSDT_HOSODALUUTRU_HOCSINH_EDIT: 'WEB_HSDT_HOSODALUUTRU_HOCSINH_EDIT',
  WEB_HSDT_PHUHUYNH_VIEW: 'WEB_HSDT_PHUHUYNH_VIEW',
  WEB_HSDT_PHUHUYNH_CREATE: 'WEB_HSDT_PHUHUYNH_CREATE',
  WEB_HSDT_PHUHUYNH_DETAIL: 'WEB_HSDT_PHUHUYNH_DETAIL',
  WEB_HSDT_PHUHUYNH_EDIT: 'WEB_HSDT_PHUHUYNH_EDIT',
  WEB_HOSODALUUTRU_PHUHUYNH_DETAIL: 'WEB_HOSODALUUTRU_PHUHUYNH_DETAIL',
  WEB_HOSODALUUTRU_PHUHUYNH_EDIT: 'WEB_HOSODALUUTRU_PHUHUYNH_EDIT',
  WEB_HSDT_PROFILEHOCSINH_VIEW: 'WEB_HSDT_PROFILEHOCSINH_VIEW',
  WEB_HSDT_HOSODALUUTRU_HOCSINH_VIEW: 'WEB_HSDT_HOSODALUUTRU_HOCSINH_VIEW',
  WEB_HSDT_HOSODALUUTRU_HOCSINH_DETAIL: 'WEB_HSDT_HOSODALUUTRU_HOCSINH_DETAIL',
  WEB_HSDT_HOSODALUUTRU_HOCSINH_EDIT: 'WEB_HSDT_HOSODALUUTRU_HOCSINH_EDIT',
  WEB_HSDT_HOSODALUUTRU_PHUHUYNH_VIEW: 'WEB_HSDT_HOSODALUUTRU_PHUHUYNH_VIEW',
  WEB_HSDT_HOSODALUUTRU_PHUHUYNH_DETAIL: 'WEB_HSDT_HOSODALUUTRU_PHUHUYNH_DETAIL',
  WEB_HSDT_HOSODALUUTRU_PHUHUYNH_EDIT: 'WEB_HSDT_HOSODALUUTRU_PHUHUYNH_EDIT',
  WEB_HSDT_CAUHINH_COSO_VIEW: 'WEB_HSDT_CAUHINH_COSO_VIEW',
  WEB_HSDT_CAUHINH_COSO_CREATE: 'WEB_HSDT_CAUHINH_COSO_CREATE',
  WEB_HSDT_CAUHINH_COSO_DETAIL: 'WEB_HSDT_CAUHINH_COSO_DETAIL',
  WEB_HSDT_CAUHINH_COSO_EDIT: 'WEB_HSDT_CAUHINH_COSO_EDIT',
  WEB_HSDT_CAUHINH_LOPHOC_VIEW: 'WEB_HSDT_CAUHINH_LOPHOC_VIEW',
  WEB_HSDT_CAUHINH_LOPHOC_CREATE: 'WEB_HSDT_CAUHINH_LOPHOC_CREATE',
  WEB_HSDT_CAUHINH_LOPHOC_DETAIL: 'WEB_HSDT_CAUHINH_LOPHOC_DETAIL',
  WEB_HSDT_CAUHINH_LOPHOC_EDIT: 'WEB_HSDT_CAUHINH_LOPHOC_EDIT',
  WEB_HSDT_BAOCAO_VIEW: 'WEB_HSDT_BAOCAO_VIEW',
  WEB_HSDT_CAUHINH_VIEW: 'WEB_HSDT_CAUHINH_VIEW',
  WEB_HSDT_HOSODALUUTRU_VIEW: 'WEB_HSDT_HOSODALUUTRU_VIEW',

  //Phân lớp
  WEB_PHANLOP_VIEW: 'WEB_PHANLOP_VIEW',
  WEB_PHANLOP_LICHSU_VIEW: 'WEB_PHANLOP_LICHSU_VIEW',
  WEB_PHANLOP_HOCSINH_XEPLOP_VIEW: 'WEB_PHANLOP_HOCSINH_XEPLOP_VIEW',
  WEB_PHANLOP_HOCSINH_CHUYENLOP_VIEW: 'WEB_PHANLOP_HOCSINH_CHUYENLOP_VIEW',
  WEB_PHANLOP_GIAOVIEN_XEPLOP_VIEW: 'WEB_PHANLOP_GIAOVIEN_XEPLOP_VIEW',
  WEB_PHANLOP_GIAOVIEN_DSGIAOVIENVATRE_VIEW: 'WEB_PHANLOP_GIAOVIEN_DSGIAOVIENVATRE_VIEW',
  WEB_PHANLOP_GIAOVIEN_DIEUCHUYEN_VIEW: 'WEB_PHANLOP_GIAOVIEN_DIEUCHUYEN_VIEW',
  WEB_PHANLOP_CAUHINHDANGKYNGOAIGIO_VIEW: 'WEB_PHANLOP_CAUHINHDANGKYNGOAIGIO_VIEW',
  WEB_PHANLOP_BAOCAO_VIEW: 'WEB_PHANLOP_BAOCAO_VIEW',
  WEB_PHANLOP_HOCSINH_VIEW: 'WEB_PHANLOP_HOCSINH_VIEW',
  WEB_PHANLOP_GIAOVIEN_VIEW: 'WEB_PHANLOP_GIAOVIEN_VIEW',
  WEB_PHANLOP_GIAOVIENPHUTRACHNGOAIGIO_VIEW: 'WEB_PHANLOP_GIAOVIENPHUTRACHNGOAIGIO_VIEW',

  //Thời khóa biểu
  WEB_TKB_VIEW: 'WEB_TKB_VIEW',
  WEB_TKB_TKBTUDONG_VIEW: 'WEB_TKB_TKBTUDONG_VIEW',
  WEB_TKB_LICHLAMVIECSUKIEN_VIEW: 'WEB_TKB_LICHLAMVIECSUKIEN_VIEW',
  WEB_TKB_TKBCUATRE_VIEW: 'WEB_TKB_TKBCUATRE_VIEW',
  WEB_TKB_LICHSU_VIEW: 'WEB_TKB_LICHSU_VIEW',
  WEB_TKB_CAUHINHTHOIGIAN_VIEW: 'WEB_TKB_CAUHINHTHOIGIAN_VIEW',
  WEB_TKB_DANHMUC_NHOMHOATDONG_VIEW: 'WEB_TKB_DANHMUC_NHOMHOATDONG_VIEW',
  WEB_TKB_THONGKETIEMCAN_VIEW: 'WEB_TKB_THONGKETIEMCAN_VIEW',
  WEB_TKB_THONGKEBAOCAO_VIEW: 'WEB_TKB_THONGKEBAOCAO_VIEW',

  //Kiến thức nuôi dạy trẻ
  WEB_KIENTHUCNUOIDAYTRE_DANHSACHBAIVIET_VIEW: 'WEB_KIENTHUCNUOIDAYTRE_DANHSACHBAIVIET_VIEW',
  WEB_KIENTHUCNUOIDAYTRE_DANHMUC_VIEW: 'WEB_KIENTHUCNUOIDAYTRE_DANHMUC_VIEW',
  WEB_KIENTHUCNUOIDAYTRE_VIEW: 'WEB_KIENTHUCNUOIDAYTRE_VIEW',

  //Điểm danh
  WEB_DIEMDANH_LICHHOC_VIEW: 'WEB_DIEMDANH_LICHHOC_VIEW',
  WEB_DIEMDANH_VIEW: 'WEB_DIEMDANH_VIEW',
  WEB_DIEMDANH_DIEMDANH_VIEW: 'WEB_DIEMDANH_DIEMDANH_VIEW',
  WEB_DIEMDANH_DONXINPHEP_VIEW: 'WEB_DIEMDANH_DONXINPHEP_VIEW',
  WEB_DIEMDANH_DONXINPHEP_CAUHINH_VIEW: 'WEB_DIEMDANH_DONXINPHEP_CAUHINH_VIEW',
  WEB_DIEMDANH_LICHHOC_LICHSURAVAOLOPAI_VIEW: 'WEB_DIEMDANH_LICHHOC_LICHSURAVAOLOPAI_VIEW',
  WEB_DIEMDANH_DONXINPHEP_CAUHINH_LOAINGHIPHEP_VIEW:
    'WEB_DIEMDANH_DONXINPHEP_CAUHINH_LOAINGHIPHEP_VIEW',
  WEB_DIEMDANH_DONXINPHEP_CAUHINH_LOAINGHIPHEP_CREATE:
    'WEB_DIEMDANH_DONXINPHEP_CAUHINH_LOAINGHIPHEP_CREATE',
  WEB_DIEMDANH_DONXINPHEP_CAUHINH_LOAINGHIPHEP_EDIT:
    'WEB_DIEMDANH_DONXINPHEP_CAUHINH_LOAINGHIPHEP_EDIT',
  WEB_DIEMDANH_DONXINPHEP_CAUHINH_LYDONGHIPHEP_VIEW:
    'WEB_DIEMDANH_DONXINPHEP_CAUHINH_LYDONGHIPHEP_VIEW',
  WEB_DIEMDANH_DONXINPHEP_CAUHINH_LYDONGHIPHEP_CREATE:
    'WEB_DIEMDANH_DONXINPHEP_CAUHINH_LYDONGHIPHEP_CREATE',
  WEB_DIEMDANH_DONXINPHEP_CAUHINH_LYDONGHIPHEP_EDIT:
    'WEB_DIEMDANH_DONXINPHEP_CAUHINH_LYDONGHIPHEP_EDIT',
  WEB_DIEMDANH_DONXINPHEP_CAUHINH_THOIGIANNGHIPHEP_VIEW:
    'WEB_DIEMDANH_DONXINPHEP_CAUHINH_THOIGIANNGHIPHEP_VIEW',
  WEB_DIEMDANH_DONXINPHEP_DONXINPHEPCHOBE_VIEW: 'WEB_DIEMDANH_DONXINPHEP_DONXINPHEPCHOBE_VIEW',
  WEB_DIEMDANH_DONXINPHEP_DONXINPHEPCHOBE_CREATE: 'WEB_DIEMDANH_DONXINPHEP_DONXINPHEPCHOBE_CREATE',
  WEB_DIEMDANH_DONXINPHEP_DONXINPHEPCHOBE_EDIT: 'WEB_DIEMDANH_DONXINPHEP_DONXINPHEPCHOBE_EDIT',
  WEB_DIEMDANH_DIEMDANH_NHAPDIEMDANH_VIEW: 'WEB_DIEMDANH_DIEMDANH_NHAPDIEMDANH_VIEW',
  WEB_DIEMDANH_DIEMDANH_THDIEMDANH_VIEW: 'WEB_DIEMDANH_DIEMDANH_THDIEMDANH_VIEW',
  WEB_DIEMDANH_DIEMDANH_LYDODIEMDANH_VIEW: 'WEB_DIEMDANH_DIEMDANH_LYDODIEMDANH_VIEW',
  WEB_DIEMDANH_DIEMDANH_LYDODIEMDANH_CREATE: 'WEB_DIEMDANH_DIEMDANH_LYDODIEMDANH_CREATE',
  WEB_DIEMDANH_DIEMDANH_LYDODIEMDANH_EDIT: 'WEB_DIEMDANH_DIEMDANH_LYDODIEMDANH_EDIT',
  WEB_DIEMDANH_LICHSUDIEMDANH_VIEW: 'WEB_DIEMDANH_LICHSUDIEMDANH_VIEW',

  //Dặn dò
  DANDO: 'DANDO',
  DANDO_DANHSACH_CHOXACNHAN: 'DANDO_DANHSACH_CHOXACNHAN',
  DANDO_DANHSACH_DANHAN: 'DANDO_DANHSACH_DANHAN',
  DANDO_DANHSACH: 'DANDO_DANHSACH',

  //Sức khỏe
  SUCKHOE: 'SUCKHOE',
  SUCKHOE_CAUHINHBINHNUOC: 'SUCKHOE_CAUHINHBINHNUOC',
  SUCKHOE_SUCKHOEHOMNAY: 'SUCKHOE_SUCKHOEHOMNAY',
  SUCKHOE_LICHSU: 'SUCKHOE_LICHSU',
  SUCKHOE_SUCKHOEHOMNAY: 'SUCKHOE_SUCKHOEHOMNAY',
  SUCKHOE_THONGKE: 'SUCKHOE_THONGKE',

  //Chương trình học
  CTH: 'CTH',
  CTH_HOCTAPGIAOCU_GOCGIAOCU: 'CTH_HOCTAPGIAOCU_GOCGIAOCU',
  CTH_HOCTAPGIAOCU_GIAOCU: 'CTH_HOCTAPGIAOCU_GIAOCU',
  CTH_HOCTAPGIAOCU_TKNC: 'CTH_HOCTAPGIAOCU_TKNC',
  CTH_BAOCAO: 'CTH_BAOCAO',
  CTH_HOCTAPGIAOCU:'CTH_HOCTAPGIAOCU',
  CTH_HOCTAPGIAOCU_HOCSINHCOTKNC: 'CTH_HOCTAPGIAOCU_HOCSINHCOTKNC',
  CTH_HOCTAPGIAOCU_HOCSINHCOTKNC_CHOGUI: 'CTH_HOCTAPGIAOCU_HOCSINHCOTKNC_CHOGUI',
  CTH_HOCTAPGIAOCU_HOCSINHCOTKNC_DAGUI: 'CTH_HOCTAPGIAOCU_HOCSINHCOTKNC_DAGUI',
  CTH_HOCTAPGIAOCU_CAUHINHTKNC: 'CTH_HOCTAPGIAOCU_CAUHINHTKNC',
  CTH_LICHSU: 'CTH_LICHSU',
  CTH_CAUHINH: 'CTH_CAUHINH',
  CTH_CAUHINH_NHOMTIEUCHI: 'CTH_CAUHINH_NHOMTIEUCHI',
  CTH_CAUHINH_THUOCNHOMTIEUCHI: 'CTH_CAUHINH_THUOCNHOMTIEUCHI',

};
export default permissions;
