export default {
  namespace: 'OPtwentyFourMonth',
  state: {
    data: [
      {
        key: 1,
        name: 'Cơ sở',
        birthDay : 'Lake view',
        month: '25',
        date: 'Tổng',
        children: [
          {
            key: 11,
            name: 'Lớp',
            date: 'Preschool 1',
            month: '12',
            children: [
              {
                key: 11,
                name: 'Nguyễn Thị Anh Thư',
                date: '14/01/2021',
                birthDay: '10/2/2017',
                age: '52',
                month: '28',
              },
              {
                key: 11,
                name: 'Trần Thùy Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '26',
              },
              {
                key: 11,
                name: 'Nguyễn Thị Minh Nguyệt',
                date: '17/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '24',
              },
              {
                key: 11,
                name: 'Trần Phương Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '20',
              },
              {
                key: 11,
                name: 'Trần Thùy Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '26',
              },
              {
                key: 11,
                name: 'Nguyễn VIệt Khoa',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '28',
              },
              {
                key: 11,
                name: 'Nguyễn Trần Khả Doanh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '26',
              },
              {
                key: 11,
                name: 'Đặng Ánh Dương',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '26',
              },
              {
                key: 11,
                name: 'Nguyễn Gia Khang',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '28',
              },
            ],
          },
          {
            key: 12,
            name: 'Lớp',
            date: 'Preschool',
            children: [
              {
                key: 12,
                name: 'Nguyễn Thị Anh Thư',
                date: '14/01/2021',
                birthDay: '10/2/2017',
                age: '52',
                month: '28',
              },
              {
                key: 12,
                name: 'Trần Thùy Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '28',
              },
              {
                key: 12,
                name: 'Nguyễn Thị Minh Nguyệt',
                date: '17/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '28',
              },
              {
                key: 12,
                name: 'Trần Phương Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '28',
              },
              {
                key: 12,
                name: 'Trần Thùy Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '27',
              },
              {
                key: 12,
                name: 'Nguyễn VIệt Khoa',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '28',
              },
              {
                key: 12,
                name: 'Nguyễn Trần Khả Doanh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '28',
              },
              {
                key: 12,
                name: 'Đặng Ánh Dương',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '27',
              },
              {
                key: 12,
                name: 'Nguyễn Gia Khang',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '28',
              },
            ],
          },
        ],
      },
      {
        key: 2,
        name: 'Scenic Valley 2',
        birthDay: 'Lake view',
        date: 'Tổng',
        children: [
          {
            key: 11,
            name: 'Lớp',
            date: 'Preschool 1',
            month: '0',
          },
        ],
      },
    ],
    pagination: {
      total: 0,
    },
    error: {
      isError: false,
      data: {},
    },
    branches: [],
    classes: [],
  },
  reducers: {
    INIT_STATE: (state) => ({ ...state }),
  },
  effects: {},
  subscriptions: {},
};
