export default {
  namespace: 'OPListStudentStudyInSummer',
  state: {
    data: [
      {
        key: 1,
        name: 'Cơ sở',
        birthDay: 'Lake view',
        children: [
          {
            key: 11,
            name: 'Lớp',
            birthDay: 'Preschool',
            children: [
              {
                key: 11,
                name: 'Trần Thùy Linh',
                birthDay: '16/10/2017',
                gender: 'FEMALE',
                age: 32,
                date: '15/01/2021',
                father_name: 'Trần Đức Hải',
                mother_name: 'Lê Thị Ngọc Sương',
                address: '111A Pasteur, Bến Nghé',
              },
              {
                key: 11,
                name: 'Nguyễn Thị Minh Nguyệt',
                birthDay: '08/05/2017',
                gender: 'FEMALE',
                age: 35,
                date: '17/01/2019',
                father_name: 'Nguyễn Văn Hùng',
                mother_name: 'Trần Ngọc Ánh',
                address: '114 Tôn Thất Đạm, Bến Nghé',
              },
            ],
          },
          {
            key: 12,
            name: 'Lớp',
            birthDay: 'Nursery',
            children: [
              {
                key: 12,
                name: 'Vũ Hoàng Ân',
                birthDay: '08/03/2017',
                gender: 'MALE',
                age: 31,
                date: '14/01/2019',
                father_name: 'Vũ Minh Hải',
                mother_name: 'Trần Phương Linh',
                address: '25 Nguyễn Thái Học, Cầu Ông Lãnh',
              },
              {
                key: 12,
                name: 'Ngô Cát Tú Nghi',
                birthDay: '10/08/2017',
                gender: 'FEMALE',
                age: 29,
                date: '15/01/2019',
                father_name: 'Ngô Cát Thức',
                mother_name: 'Lê Thảo Nguyên',
                address: '90 Trần Đình Xu, Cô Giang',
              },
            ],
          },
        ],
      },
      {
        key: 2,
        name: 'Cơ sở',
        birthDay: 'Lake view',
        children: [
          {
            key: 13,
            name: 'Lớp',
            birthDay: 'Preschool',
            children: [
              {
                key: 13,
                name: 'Trần Thùy Linh',
                birthDay: '16/10/2017',
                gender: 'FEMALE',
                age: 32,
                date: '15/01/2021',
                father_name: 'Trần Đức Hải',
                mother_name: 'Lê Thị Ngọc Sương',
                address: '111A Pasteur, Bến Nghé',
              },
              {
                key: 13,
                name: 'Nguyễn Thị Minh Nguyệt',
                birthDay: '08/05/2017',
                gender: 'FEMALE',
                age: 35,
                date: '17/01/2019',
                father_name: 'Nguyễn Văn Hùng',
                mother_name: 'Trần Ngọc Ánh',
                address: '114 Tôn Thất Đạm, Bến Nghé',
              },
            ],
          },
          {
            key: 14,
            name: 'Lớp',
            birthDay: 'Nursery',
            children: [
              {
                key: 14,
                name: 'Vũ Hoàng Ân',
                birthDay: '08/03/2017',
                gender: 'MALE',
                age: 31,
                date: '14/01/2019',
                father_name: 'Vũ Minh Hải',
                mother_name: 'Trần Phương Linh',
                address: '25 Nguyễn Thái Học, Cầu Ông Lãnh',
              },
              {
                key: 14,
                name: 'Ngô Cát Tú Nghi',
                birthDay: '10/08/2017',
                gender: 'FEMALE',
                age: 29,
                date: '15/01/2019',
                father_name: 'Ngô Cát Thức',
                mother_name: 'Lê Thảo Nguyên',
                address: '90 Trần Đình Xu, Cô Giang',
              },
            ],
          },
        ],
      },
    ],
    pagination: {
      total: 0,
    },
    error: {
      isError: false,
      data: {},
    },
    branches: [],
    classes: [],
  },
  reducers: {
    INIT_STATE: (state) => ({ ...state }),
  },
  effects: {},
  subscriptions: {},
};
