export default {
  namespace: 'OPSixMonth',
  state: {
    data: [
      {
        key: 1,
        name: 'Cơ sở',
        date: 'Lake view',
        children: [
          {
            key: 11,
            name: 'Lớp',
            date: 'Preschool 1',
            children: [
              {
                key: 11,
                name: 'Nguyễn Thị Anh Thư',
                date: '14/01/2021',
                birthDay: '10/2/2017',
                age: '52',
                month: '5tháng16ngày',
              },
              {
                key: 11,
                name: 'Trần Thùy Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
              {
                key: 11,
                name: 'Nguyễn Thị Minh Nguyệt',
                date: '17/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
              {
                key: 11,
                name: 'Trần Phương Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
              {
                key: 11,
                name: 'Trần Thùy Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng27ngày	',
              },
              {
                key: 11,
                name: 'Nguyễn VIệt Khoa',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
              {
                key: 11,
                name: 'Nguyễn Trần Khả Doanh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
              {
                key: 11,
                name: 'Đặng Ánh Dương',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng27ngày	',
              },
              {
                key: 11,
                name: 'Nguyễn Gia Khang',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
            ],
          },
          {
            key: 12,
            name: 'Lớp',
            date: 'Preschool',
            children: [
              {
                key: 12,
                name: 'Nguyễn Thị Anh Thư',
                date: '14/01/2021',
                birthDay: '10/2/2017',
                age: '52',
                month: '5tháng16ngày',
              },
              {
                key: 12,
                name: 'Trần Thùy Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
              {
                key: 12,
                name: 'Nguyễn Thị Minh Nguyệt',
                date: '17/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
              {
                key: 12,
                name: 'Trần Phương Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
              {
                key: 12,
                name: 'Trần Thùy Linh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng27ngày	',
              },
              {
                key: 12,
                name: 'Nguyễn VIệt Khoa',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
              {
                key: 12,
                name: 'Nguyễn Trần Khả Doanh',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
              {
                key: 12,
                name: 'Đặng Ánh Dương',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng27ngày	',
              },
              {
                key: 12,
                name: 'Nguyễn Gia Khang',
                date: '15/01/2021',
                birthDay: '16/10/2017',
                age: '52',
                month: '5tháng15ngày	',
              },
            ],
          },
        ],
      },
      {
        key: 2,
        name: 'Scenic Valley 2',
        date: 'Lake view',
        children: [
          {
            key: 11,
            name: 'Lớp',
            date: 'Preschool 1',
          },
        ],
      },
    ],
    pagination: {
      total: 0,
    },
    error: {
      isError: false,
      data: {},
    },
    branches: [],
    classes: [],
  },
  reducers: {
    INIT_STATE: (state) => ({ ...state }),
  },
  effects: {},
  subscriptions: {},
};
