<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TourGuidesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('tour_guides')->delete();

        \DB::table('tour_guides')->insert(array(
            0 =>
            array(
                'id' => 'ef49c06e-d014-45d8-b784-7cfdbd9e3456',
                'full_name' => 'Nguyễn Văn B',
                'sex' => 0,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => NULL,
                'card_number' => NULL,
                'language_id' => NULL,
                'object_type_id' => NULL,
                'expiration_date' => NULL,
                'degree' => NULL,
                'professional_certificate' => NULL,
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'HDV bất hợp pháp',
                'type' => 0,
                'created_at' => '2021-11-26 15:24:35',
                'updated_at' => '2021-11-26 15:24:35',
                'deleted_at' => NULL,
            ),
            1 =>
            array(
                'id' => '7b98446c-2ef1-4c10-9487-41e008cda203',
                'full_name' => 'Nguyễn Văn C',
                'sex' => 1,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => NULL,
                'card_number' => NULL,
                'language_id' => NULL,
                'object_type_id' => NULL,
                'expiration_date' => NULL,
                'degree' => NULL,
                'professional_certificate' => NULL,
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'HDV bất hợp pháp',
                'type' => 0,
                'created_at' => '2021-11-26 15:24:45',
                'updated_at' => '2021-11-26 15:24:45',
                'deleted_at' => NULL,
            ),
            2 =>
            array(
                'id' => '4aa58748-a62b-4b31-b303-7f5f6e03d037',
                'full_name' => 'Nguyễn Văn D',
                'sex' => 1,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => NULL,
                'card_number' => NULL,
                'language_id' => NULL,
                'object_type_id' => NULL,
                'expiration_date' => NULL,
                'degree' => NULL,
                'professional_certificate' => NULL,
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'HDV bất hợp pháp',
                'type' => 0,
                'created_at' => '2021-11-26 15:24:49',
                'updated_at' => '2021-11-26 15:24:49',
                'deleted_at' => NULL,
            ),
            3 =>
            array(
                'id' => '9755a623-8327-416a-a02e-a59bc4d2543c',
                'full_name' => 'Nguyễn Văn E',
                'sex' => 1,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => NULL,
                'card_number' => NULL,
                'language_id' => NULL,
                'object_type_id' => NULL,
                'expiration_date' => NULL,
                'degree' => NULL,
                'professional_certificate' => NULL,
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'HDV bất hợp pháp',
                'type' => 0,
                'created_at' => '2021-11-26 15:24:53',
                'updated_at' => '2021-11-26 15:24:53',
                'deleted_at' => NULL,
            ),
            4 =>
            array(
                'id' => '4a0c2879-7589-44f2-b63c-fb02b90ef90f',
                'full_name' => 'Nguyễn Văn F',
                'sex' => 1,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => NULL,
                'card_number' => NULL,
                'language_id' => NULL,
                'object_type_id' => NULL,
                'expiration_date' => NULL,
                'degree' => NULL,
                'professional_certificate' => NULL,
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'HDV bất hợp pháp',
                'type' => 0,
                'created_at' => '2021-11-26 15:24:56',
                'updated_at' => '2021-11-26 15:24:56',
                'deleted_at' => NULL,
            ),
            5 =>
            array(
                'id' => '1bc075fe-3aee-4dbb-b81c-6bfab6d0ee7e',
                'full_name' => 'Nguyễn Văn F',
                'sex' => 1,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => 'babee3af-d5a4-4906-80f3-a70f115e96f9',
                'card_number' => '148170229',
                'language_id' => 'e3786657-485f-4bd3-94fb-6c801c25eec9',
                'object_type_id' => NULL,
                'expiration_date' => '2023-05-05',
                'degree' => 'Cử nhân Đại học Ngoại Ngữ',
                'professional_certificate' => 'Chứng chỉ nghiệp vụ HDV quốc tế',
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'HDV hợp pháp',
                'type' => 1,
                'created_at' => '2021-11-26 15:29:00',
                'updated_at' => '2021-11-26 15:29:00',
                'deleted_at' => NULL,
            ),
            6 =>
            array(
                'id' => '61791cb2-a281-4855-ab43-b9c3d40ff357',
                'full_name' => 'Nguyễn Văn FF',
                'sex' => 1,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => 'babee3af-d5a4-4906-80f3-a70f115e96f9',
                'card_number' => '148170229',
                'language_id' => 'e3786657-485f-4bd3-94fb-6c801c25eec9',
                'object_type_id' => NULL,
                'expiration_date' => '2023-05-05',
                'degree' => 'Cử nhân Đại học Ngoại Ngữ',
                'professional_certificate' => 'Chứng chỉ nghiệp vụ HDV quốc tế',
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'HDV hợp pháp',
                'type' => 1,
                'created_at' => '2021-11-26 15:29:06',
                'updated_at' => '2021-11-26 15:29:06',
                'deleted_at' => NULL,
            ),
            7 =>
            array(
                'id' => '9aef275c-0b5c-42c1-b064-67da3eff5e21',
                'full_name' => 'Nguyễn Văn A',
                'sex' => 1,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => 'babee3af-d5a4-4906-80f3-a70f115e96f9',
                'card_number' => '148170229',
                'language_id' => 'e3786657-485f-4bd3-94fb-6c801c25eec9',
                'object_type_id' => NULL,
                'expiration_date' => '2023-05-05',
                'degree' => 'Cử nhân Đại học Ngoại Ngữ',
                'professional_certificate' => 'Chứng chỉ nghiệp vụ HDV quốc tế',
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'HDV hợp pháp',
                'type' => 1,
                'created_at' => '2021-11-26 15:29:11',
                'updated_at' => '2021-11-26 15:29:11',
                'deleted_at' => NULL,
            ),
            8 =>
            array(
                'id' => 'f6cc431c-6f3a-4d0d-9554-fe348afabb07',
                'full_name' => 'Nguyễn Văn Z',
                'sex' => 0,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => 'babee3af-d5a4-4906-80f3-a70f115e96f9',
                'card_number' => '148170229',
                'language_id' => 'e3786657-485f-4bd3-94fb-6c801c25eec9',
                'object_type_id' => NULL,
                'expiration_date' => '2023-05-05',
                'degree' => 'Cử nhân Đại học Ngoại Ngữ',
                'professional_certificate' => 'Chứng chỉ nghiệp vụ HDV quốc tế',
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'HDV hợp pháp',
                'type' => 1,
                'created_at' => '2021-11-26 15:29:18',
                'updated_at' => '2021-11-26 15:29:18',
                'deleted_at' => NULL,
            ),
            9 =>
            array(
                'id' => 'f454c425-7cd7-4b19-bbd4-ec1b86bb0067',
                'full_name' => 'Nguyễn Văn Y',
                'sex' => 0,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => 'babee3af-d5a4-4906-80f3-a70f115e96f9',
                'card_number' => '148170229',
                'language_id' => 'e3786657-485f-4bd3-94fb-6c801c25eec9',
                'object_type_id' => NULL,
                'expiration_date' => '2023-05-05',
                'degree' => 'Cử nhân Đại học Ngoại Ngữ',
                'professional_certificate' => 'Chứng chỉ nghiệp vụ HDV quốc tế',
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'HDV hợp pháp',
                'type' => 1,
                'created_at' => '2021-11-26 15:29:21',
                'updated_at' => '2021-11-26 15:29:21',
                'deleted_at' => NULL,
            ),
            10 =>
            array(
                'id' => '1558c80d-ca60-46a0-8c0a-8580d40f5d91',
                'full_name' => 'Nguyễn Văn M',
                'sex' => 0,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => NULL,
                'card_number' => NULL,
                'language_id' => NULL,
                'object_type_id' => '81084ab1-2c2a-49ca-b152-98bd90b6112b',
                'expiration_date' => NULL,
                'degree' => NULL,
                'professional_certificate' => NULL,
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'Đối tượng cần theo dõi',
                'type' => 2,
                'created_at' => '2021-11-26 15:31:26',
                'updated_at' => '2021-11-26 15:31:26',
                'deleted_at' => NULL,
            ),
            11 =>
            array(
                'id' => 'f8d35d0f-1b79-403e-a366-44183071e78d',
                'full_name' => 'Nguyễn Văn N',
                'sex' => 0,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => NULL,
                'card_number' => NULL,
                'language_id' => NULL,
                'object_type_id' => 'a56536bc-7957-4f28-8241-a6959483ddd3',
                'expiration_date' => NULL,
                'degree' => NULL,
                'professional_certificate' => NULL,
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'Đối tượng cần theo dõi',
                'type' => 2,
                'created_at' => '2021-11-26 15:31:40',
                'updated_at' => '2021-11-26 15:31:40',
                'deleted_at' => NULL,
            ),
            12 =>
            array(
                'id' => 'cac60497-2fb9-4547-912a-0942975ebcb9',
                'full_name' => 'Nguyễn Văn T',
                'sex' => 0,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => NULL,
                'card_number' => NULL,
                'language_id' => NULL,
                'object_type_id' => 'ac9ad52f-52ab-4bb9-9c71-d4107a7fdc2b',
                'expiration_date' => NULL,
                'degree' => NULL,
                'professional_certificate' => NULL,
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'Đối tượng cần theo dõi',
                'type' => 2,
                'created_at' => '2021-11-26 15:31:56',
                'updated_at' => '2021-11-26 15:31:56',
                'deleted_at' => NULL,
            ),
            13 =>
            array(
                'id' => '11b0197f-7e4b-4746-9230-ed6f1793ef7c',
                'full_name' => 'Nguyễn Văn P',
                'sex' => 0,
                'id_card' => '123456789',
                'date_of_birth' => '1996-01-01',
                'card_type_id' => NULL,
                'card_number' => NULL,
                'language_id' => NULL,
                'object_type_id' => 'd2321118-a242-4c73-83ac-53a100ed4dc8',
                'expiration_date' => NULL,
                'degree' => NULL,
                'professional_certificate' => NULL,
                'nationality' => 'VN',
                'home_town' => 'DN',
                'resident' => 'HK',
                'note' => 'Đối tượng cần theo dõi',
                'type' => 2,
                'created_at' => '2021-11-26 15:32:07',
                'updated_at' => '2021-11-26 15:32:07',
                'deleted_at' => NULL,
            ),
        ));
    }
}
