<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TravelAgenciesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('travel_agencies')->delete();
        
        \DB::table('travel_agencies')->insert(array (
            0 => 
            array (
                'id' => '325af695-fbaf-478c-a216-7bce39fab291',
                'name' => 'Công ty TNHH Dịch vụ và Du lịch Hương Biển Việt',
                'representative_name' => 'Tô My Hồng Oanh',
                'representative_phone' => '0913644699',
                'english_name' => 'Huong Bien Viet Tourist and Service Company Limited',
                'number_of_seasonal_worker' => 10,
                'travel_permit' => 'Giấy phép',
                'account_name' => 'luhanh399',
                'service_type' => 0,
                'license_date' => '2019-01-01',
                'phone' => '023635550050',
                'status' => 'abc',
                'operator_name' => 'Tên người điều hành',
                'operator_phone' => '023635550050',
                'address' => '357 Phan Châu Trinh, Quận Hải Châu, Đà Nẵng',
                'license_number' => '56-146/2020/TCDL-GP LHQT',
                'email' => 'gm@merperle.vn',
                'date_range' => '2019-01-01',
                'reporter_name' => 'Lê Thị Ngọc Quỳnh',
                'reporter_phone' => '023635550050',
                'fax' => '55000',
                'exploiting_international_visitor_market' => 'Thị trường khách quốc tế khai thác',
                'website' => 'silverseadanang.com',
                'number_of_regular_employee' => '20',
                'total_number_of_registered_vehicle' => '20',
                'locality' => 0,
                'tax_code' => '0401946050',
                'note' => 'ghi chú',
                'created_at' => '2021-11-26 15:42:40',
                'updated_at' => '2021-11-26 15:42:40',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => '4837993e-9211-4fe8-a726-ed71454f8183',
                'name' => 'Công Ty TNHH TMDV Lữ Hành Quốc Tế Libra',
                'representative_name' => 'Tô My Hồng Oanh',
                'representative_phone' => '0913644699',
                'english_name' => 'Huong Bien Viet Tourist and Service Company Limited',
                'number_of_seasonal_worker' => 10,
                'travel_permit' => 'Giấy phép',
                'account_name' => 'luhanh399',
                'service_type' => 1,
                'license_date' => '2019-01-01',
                'phone' => '023635550050',
                'status' => 'abc',
                'operator_name' => 'Tên người điều hành',
                'operator_phone' => '023635550050',
                'address' => '357 Phan Châu Trinh, Quận Hải Châu, Đà Nẵng',
                'license_number' => '56-146/2020/TCDL-GP LHQT',
                'email' => 'gm@merperle.vn',
                'date_range' => '2019-01-01',
                'reporter_name' => 'Lê Thị Ngọc Quỳnh',
                'reporter_phone' => '023635550050',
                'fax' => '55000',
                'exploiting_international_visitor_market' => 'Thị trường khách quốc tế khai thác',
                'website' => 'silverseadanang.com',
                'number_of_regular_employee' => '20',
                'total_number_of_registered_vehicle' => '20',
                'locality' => 1,
                'tax_code' => '0401946050',
                'note' => 'ghi chú',
                'created_at' => '2021-11-26 15:43:00',
                'updated_at' => '2021-11-26 15:43:00',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => '86c36cc6-51c6-4d66-b611-23dd3d8fcc18',
                'name' => 'Công Ty TNHH TM & Du Lịch Quảng Đà Thành Đà Nẵng',
                'representative_name' => 'Tô My Hồng Oanh',
                'representative_phone' => '0913644699',
                'english_name' => 'Huong Bien Viet Tourist and Service Company Limited',
                'number_of_seasonal_worker' => 10,
                'travel_permit' => 'Giấy phép',
                'account_name' => 'luhanh399',
                'service_type' => 2,
                'license_date' => '2019-01-01',
                'phone' => '023635550050',
                'status' => 'abc',
                'operator_name' => 'Tên người điều hành',
                'operator_phone' => '023635550050',
                'address' => '357 Phan Châu Trinh, Quận Hải Châu, Đà Nẵng',
                'license_number' => '56-146/2020/TCDL-GP LHQT',
                'email' => 'gm@merperle.vn',
                'date_range' => '2019-01-01',
                'reporter_name' => 'Lê Thị Ngọc Quỳnh',
                'reporter_phone' => '023635550050',
                'fax' => '55000',
                'exploiting_international_visitor_market' => 'Thị trường khách quốc tế khai thác',
                'website' => 'silverseadanang.com',
                'number_of_regular_employee' => '20',
                'total_number_of_registered_vehicle' => '20',
                'locality' => 1,
                'tax_code' => '0401946050',
                'note' => 'ghi chú',
                'created_at' => '2021-11-26 15:43:16',
                'updated_at' => '2021-11-26 15:43:16',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => '94e6b68c-f534-4d89-b907-f56f6720c98d',
                'name' => 'Công Ty Cổ Phần Du Lịch Viet Dragon Đà Nẵng',
                'representative_name' => 'Tô My Hồng Oanh',
                'representative_phone' => '0913644699',
                'english_name' => 'Huong Bien Viet Tourist and Service Company Limited',
                'number_of_seasonal_worker' => 10,
                'travel_permit' => 'Giấy phép',
                'account_name' => 'luhanh399',
                'service_type' => 3,
                'license_date' => '2019-01-01',
                'phone' => '023635550050',
                'status' => 'abc',
                'operator_name' => 'Tên người điều hành',
                'operator_phone' => '023635550050',
                'address' => '357 Phan Châu Trinh, Quận Hải Châu, Đà Nẵng',
                'license_number' => '56-146/2020/TCDL-GP LHQT',
                'email' => 'gm@merperle.vn',
                'date_range' => '2019-01-01',
                'reporter_name' => 'Lê Thị Ngọc Quỳnh',
                'reporter_phone' => '023635550050',
                'fax' => '55000',
                'exploiting_international_visitor_market' => 'Thị trường khách quốc tế khai thác',
                'website' => 'silverseadanang.com',
                'number_of_regular_employee' => '20',
                'total_number_of_registered_vehicle' => '20',
                'locality' => 1,
                'tax_code' => '0401946050',
                'note' => 'ghi chú',
                'created_at' => '2021-11-26 15:43:28',
                'updated_at' => '2021-11-26 15:43:28',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => '877e67d5-a627-4f65-b950-9c9108c371f8',
                'name' => 'Công Ty Cổ Phần Du Lịch Việt Nam Vitours',
                'representative_name' => 'Tô My Hồng Oanh',
                'representative_phone' => '0913644699',
                'english_name' => 'Huong Bien Viet Tourist and Service Company Limited',
                'number_of_seasonal_worker' => 10,
                'travel_permit' => 'Giấy phép',
                'account_name' => 'luhanh399',
                'service_type' => 4,
                'license_date' => '2019-01-01',
                'phone' => '023635550050',
                'status' => 'abc',
                'operator_name' => 'Tên người điều hành',
                'operator_phone' => '023635550050',
                'address' => '357 Phan Châu Trinh, Quận Hải Châu, Đà Nẵng',
                'license_number' => '56-146/2020/TCDL-GP LHQT',
                'email' => 'gm@merperle.vn',
                'date_range' => '2019-01-01',
                'reporter_name' => 'Lê Thị Ngọc Quỳnh',
                'reporter_phone' => '023635550050',
                'fax' => '55000',
                'exploiting_international_visitor_market' => 'Thị trường khách quốc tế khai thác',
                'website' => 'silverseadanang.com',
                'number_of_regular_employee' => '20',
                'total_number_of_registered_vehicle' => '20',
                'locality' => 1,
                'tax_code' => '0401946050',
                'note' => 'ghi chú',
                'created_at' => '2021-11-26 15:43:37',
                'updated_at' => '2021-11-26 15:43:37',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => '8392c42a-71a8-4347-8261-1a477bbb3e87',
                'name' => 'Công Ty Du Lịch TransViet Đà Nẵng',
                'representative_name' => 'Tô My Hồng Oanh',
                'representative_phone' => '0913644699',
                'english_name' => 'Huong Bien Viet Tourist and Service Company Limited',
                'number_of_seasonal_worker' => 10,
                'travel_permit' => 'Giấy phép',
                'account_name' => 'luhanh399',
                'service_type' => 5,
                'license_date' => '2019-01-01',
                'phone' => '023635550050',
                'status' => 'abc',
                'operator_name' => 'Tên người điều hành',
                'operator_phone' => '023635550050',
                'address' => '357 Phan Châu Trinh, Quận Hải Châu, Đà Nẵng',
                'license_number' => '56-146/2020/TCDL-GP LHQT',
                'email' => 'gm@merperle.vn',
                'date_range' => '2019-01-01',
                'reporter_name' => 'Lê Thị Ngọc Quỳnh',
                'reporter_phone' => '023635550050',
                'fax' => '55000',
                'exploiting_international_visitor_market' => 'Thị trường khách quốc tế khai thác',
                'website' => 'silverseadanang.com',
                'number_of_regular_employee' => '20',
                'total_number_of_registered_vehicle' => '20',
                'locality' => 1,
                'tax_code' => '0401946050',
                'note' => 'ghi chú',
                'created_at' => '2021-11-26 15:43:48',
                'updated_at' => '2021-11-26 15:43:48',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}